site_name: Advanced Peripherals
site_url: 'https://docs.intelligence-modding.de/'

nav:
    - 'Home': 'index.md'
    - 'Guides':
      - 'How to: report a bug or request a feature': 'guides/how_to_report.md'
      - 'Item and Fluid Filters': 'guides/filters.md'
      - 'Cooldowns and Fuel consumption': 'guides/cooldowns_and_fuel_consumption.md'
    - 'Peripherals':
      - 'Chat Box': 'peripherals/chat_box.md'
      - 'Energy Detector': 'peripherals/energy_detector.md'
      - 'Environment Detector': 'peripherals/environment_detector.md'
      - 'Player Detector': 'peripherals/player_detector.md'
      - 'Inventory Manager': 'peripherals/inventory_manager.md'
      - 'NBT Storage': 'peripherals/nbt_storage.md'
      - 'Block Reader': 'peripherals/block_reader.md'
      - 'Geo Scanner': 'peripherals/geo_scanner.md'
      - 'Redstone Integrator': 'peripherals/redstone_integrator.md'
      - 'AR Controller': 'peripherals/ar_controller.md'
      - 'ME Bridge': 'peripherals/me_bridge.md'
      - 'RS Bridge': 'peripherals/rs_bridge.md'
      - 'Colony Integrator': 'peripherals/colony_integrator.md'
    - 'Turtles':
      - 'Chatty Turtle': 'turtles/chatty_turtle.md'
      - 'Chunky Turtle': 'turtles/chunky_turtle.md'
      - 'Environment Turtle': 'turtles/environment_turtle.md'
      - 'Player Turtle': 'turtles/player_turtle.md'
      - 'Geoscanning Turtle': 'turtles/geo_scanner_turtle.md'
      - 'Metaphysics':
        - 'Weak Automata': 'turtles/metaphysics/weak_automata.md'
        - 'Husbandry Automata': 'turtles/metaphysics/husbandry_automata.md'
        - 'End Automata': 'turtles/metaphysics/end_automata.md'
        - 'Overpowered Automata': 'turtles/metaphysics/overpowered_automata.md'
    - 'Items':
      - 'AR Goggles': 'items/ar_goggles.md'
      - 'Chunk Controller': 'items/chunk_controller.md'
      - 'Computer Tool': 'items/computer_tool.md'
      - 'Memory Card': 'items/memory_card.md'
      - 'Pocket Computers': 'items/pocket_computer.md'
    - 'Mod Integrations':
      - 'integrations/index.md'
      - 'Minecraft':
        - 'Beacon': 'integrations/minecraft/beacon.md'
        - 'Note Block': 'integrations/minecraft/noteblock.md'
      - 'Botania':
        - 'Flowers': 'integrations/botania/flowers.md'
        - 'Mana Pool': 'integrations/botania/pool.md'
        - 'Mana Spreader': 'integrations/botania/spreader.md'
      - 'Create':
        - 'Basin': 'integrations/create/basin.md'
        - 'Blaze Burner': 'integrations/create/blazeburner.md'
        - 'Fluid Tank': 'integrations/create/fluidtank.md'
        - 'Mechanical Mixer': 'integrations/create/mechanicalmixer.md'
        - 'Blocks with Scroll Behaviour': 'integrations/create/scrollbehaviour.md'
      - 'Draconic Evolution':
        - 'integrations/draconic_evolution/index.md'
        # - 'Energy Core': 'integrations/draconic_evolution/energy_core.md'
        # - 'Reactor': 'integrations/draconic_evolution/reactor.md'
      - 'Immersive Engineering':
        - 'Redstone Wire Connector': 'integrations/immersive_engineering/connector.md'
        - 'Redstone Probe': 'integrations/immersive_engineering/probe.md'
      - 'Integrated Dynamics':
        - 'Variable Store': 'integrations/integrated_dynamics/variable_store.md'
      - 'Mekanism':
        - 'integrations/mekanism/index.md'
        # - 'Boiler Valve': ''
        # - 'Induction Valve': ''
        # - 'Chemical Tank': ''
        # - 'Dynamic Tank': ''
        # - 'Fluid Tank': ''
        # - 'Digital Miner': ''
        # - 'Fission': ''
        # - 'Fusion': ''
        # - 'Solar Evaporation': ''
        # - 'Transmitter': ''
        # - 'Turbine': ''
        # - 'Waste Barrel': ''
        # - 'Energy Blocks': ''
      - 'Powah':
        - 'Energy cell': 'integrations/powah/energy_cell.md'
        - 'Furnator': 'integrations/powah/furnator.md'
        - 'Magmator': 'integrations/powah/magmator.md'
        - 'Reactor': 'integrations/powah/reactor.md'
        - 'Solar panel': 'integrations/powah/solar_panel.md'
        - 'Thermo generator': 'integrations/powah/thermo_generator.md'
      - 'Storage Drawers':
        - 'Drawer': 'integrations/storage_drawers/drawer.md'
    - 'Changelogs':
      - 'Changelog 0.7.24r': 'changelogs/0.7.24r.md'
      - 'Changelog 0.7r': 'changelogs/0.7r.md'

watch:
  - overrides

theme:
    name: material
    custom_dir: overrides
    features:
      - navigation.top
      # - navigation.instant # Breaks 'lightgallery' extension
      - navigation.indexes
      - navigation.tabs
      # - navigation.sections # Makes navigation too long
      - content.code.annotate
      - content.code.copy
    palette:
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search:
      lang: en
  - glightbox
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: '中文'
          build: true
          site_name: 高级外设
          nav_translations:
            Home: '首页'
            Guides: '指南'
            'How to: report a bug or request a feature': '如何反馈bug或提出建议'
            'Item and Fluid Filters': '物品和流体过滤器'
            'Cooldowns and Fuel consumption': '冷却时间和燃料消耗'
            'Peripherals': '外设'
            'Chat Box': '聊天方块'
            'Energy Detector': '能量侦测器'
            'Environment Detector': '环境监测仪'
            'Player Detector': '玩家侦测器'
            'Inventory Manager': '库存管理器'
            'NBT Storage': 'NBT存储器'
            'Block Reader': '方块读取器'
            'Geo Scanner': '地理扫描仪'
            'Redstone Integrator': '红石接口'
            'AR Controller': 'AR控制器'
            'ME Bridge': 'ME 网关'
            'RS Bridge': 'RS 网关'
            'Colony Integrator': '殖民地集成器'
            'Turtles': '海龟'
            'Chatty Turtle': '聊天海龟'
            'Chunky Turtle': '区块海龟'
            'Environment Turtle': '环境海龟'
            'Player Turtle': '玩家海龟'
            'Geoscanning Turtle': '地理扫描仪海龟'
            'Metaphysics': 'Metaphysics'
            'Weak Automata': 'Weak Automata'
            'Husbandry Automata': 'Husbandry Automata'
            'End Automata': 'End Automata'
            'Overpowered Automata': 'Overpowered Automata'
            'Items': ’物品
            'AR Goggles': 'AR 眼镜'
            'Chunk Controller': '区块控制器'
            'Computer Tool': '电脑扳手'
            'Memory Card': '内存卡'
            'Pocket Computers': '便携电脑'
            'Mod Integrations': 'Mod 集成'
            'Minecraft': '我的世界原版'
            'Beacon': '信标'
            'Note Block': '音符盒'
            'Botania': '植物魔法'
            'Flowers': '花'
            'Mana Pool': '魔力池'
            'Mana Spreader': '魔力发射器'
            'Create': '机械动力'
            'Basin': '工作盆'
            'Blaze Burner': '烈焰人燃烧室'
            'Fluid Tank': '流体储罐'
            'Mechanical Mixer': '动力搅拌器'
            'Blocks with Scroll Behaviour': '滚动方块'
            'Draconic Evolution': '龙之进化'
            'Immersive Engineering': '沉浸工程'
            'Redstone Wire Connector': '红石接线器'
            'Redstone Probe': '红石探测接线器'
            'Integrated Dynamics': '集成动力'
            'Variable Store': '变量卡箱'
            'Mekanism': '通用机械'
            'Powah': 'Powah'
            'Energy cell': '能量单元'
            'Furnator': '熔炉发电机'
            'Magmator': '岩浆发电机'
            'Reactor': '反应堆'
            'Solar panel': '太阳能板'
            'Thermo generator': '热力发电机'
            'Storage Drawers': '储物抽屉'
            'Drawer': '抽屉'
            'Changelogs': '修改日志'
            'Changelog 0.7.24r': '修改日志 0.7.24r'
            'Changelog 0.7r': '修改日志 0.7r'

extra_css:
  - extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

repo_url: https://github.com/SirEndii/AdvancedPeripherals
repo_name: SirEndii/AdvancedPeripherals
edit_uri: edit/main/docs/

markdown_extensions:
    - mdx_math
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.tasklist:
        custom_checkbox: true
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - admonition
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
